### ISSUE TITLE
roleArn

### ISSUE THREAD

**Issue by yifeim** [aws-samples/amazon-personalize-samples#42] opened 2019-09-17 01:22 UTC
Missing roleArn in [2.View_Campaign_And_Interactions](https://github.com/aws-samples/amazon-personalize-samples/blob/master/getting_started/2.View_Campaign_And_Interactions.ipynb) and [personalize_sample_notebook](https://github.com/aws-samples/amazon-personalize-samples/blob/master/personalize_sample_notebook.ipynb).

**Comment by chrisking** [comment] 2019-09-17 10:09
@yifeim can you specify where this is needed in the View campaign notebook?

**Comment by chrisking** [comment] 2019-09-17 10:09
also it is definitely in the sample notebook as `role_arn`

**Comment by chrisking** [comment] 2019-10-07 18:53
Could not reproduce, closing now.

**Closed by chrisking** 2019-10-07 18:53 UTC
